[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc = "0.8.25"

# Try to make sure the optimizer doesn't touch the output in a way that can break
# source maps for debugging.
# via_ir = false
# optimizer = false
# optimizer_runs = 0
# optimizer_steps = 0

# These settings should be used for snapshots
optimizer = true
optimizer_runs = 1000000

bytecode_hash = "none"
cbor_metadata = false

# Needed for dotrain compose
ffi = true

[fuzz]
runs = 1024
